Fix: weights should be float64
galeone/fitbit pull request #8
Opened 2024-08-04 11:25 UTC by till

Fixes the following error:

```
json: cannot unmarshal number 100.5 into Go struct field WeightGoal.goal.startWeight of type int64
```

2024-08-04 14:27 UTC, till commented
Added a second commit for reading the nutrition log. If you prefer 2 PRs and have any feedback, lmk. :)

2024-08-04 15:55 UTC, galeone commented
Hey thank you for this PR! I just left a comment that I'd like you to address. Thanks for spotting the type issue though

2024-08-04 21:00 UTC, till commented
@galeone I don't see the comment yet, but yeah... let me know. :)

2024-08-05 04:29 UTC, galeone requested changes

2024-08-05 04:29 UTC, galeone commented on types/nutrition.go
> +	LoggedFood struct {
Can you remove the nested structs and declare the types outside?
e.g. A type `LoggedFood` and a type `Nutritional` with an optional (`json:"-"`) value for the `Water` field.

This way you can re-use the same data type for FoodLog.LoggedFoor and for FoodLogList.Summary

2024-08-05 04:30 UTC, galeone commented
> @galeone I don't see the comment yet, but yeah... let me know. :)

O forgot to submit lol

2024-08-05 06:32 UTC, till commented on types/nutrition.go
> +	LoggedFood struct {
Updated, though I think `"-"` would ignore it everywhere, I did an `omitempty`. And that seems to work. :)

2024-08-05 08:07 UTC, galeone approved these changes

2024-08-05 08:08 UTC, merged

2024-08-05 08:09 UTC, galeone commented
Merged, thanks! You can `go get` version 2.1.0 containing your changes